"""Composition and rendering tools for code-musics."""

from code_musics.automation import AutomationSegment, AutomationSpec, AutomationTarget
from code_musics.composition import (
    ArticulationSpec,
    MeteredSectionSpec,
    RhythmCell,
    bar_automation,
    canon,
    echo,
    grid_canon,
    grid_line,
    grid_ratio_line,
    grid_sequence,
    legato,
    line,
    metered_sections,
    progression,
    recontextualize_phrase,
    sequence,
    staccato,
    voiced_ratio_chord,
)
from code_musics.humanize import (
    DriftSpec,
    EnvelopeHumanizeSpec,
    TimingHumanizeSpec,
    VelocityHumanizeSpec,
)
from code_musics.meter import B, E, H, M, Q, S, SwingSpec, Timeline, W, dotted, triplet
from code_musics.pitch_motion import PitchMotionSpec
from code_musics.score import VelocityParamMap

__all__ = [
    "AutomationSegment",
    "AutomationSpec",
    "AutomationTarget",
    "B",
    "ArticulationSpec",
    "DriftSpec",
    "E",
    "EnvelopeHumanizeSpec",
    "H",
    "M",
    "MeteredSectionSpec",
    "PitchMotionSpec",
    "Q",
    "RhythmCell",
    "S",
    "Timeline",
    "TimingHumanizeSpec",
    "SwingSpec",
    "VelocityHumanizeSpec",
    "VelocityParamMap",
    "W",
    "bar_automation",
    "canon",
    "dotted",
    "echo",
    "grid_canon",
    "grid_line",
    "grid_ratio_line",
    "grid_sequence",
    "legato",
    "line",
    "metered_sections",
    "progression",
    "recontextualize_phrase",
    "sequence",
    "staccato",
    "triplet",
    "voiced_ratio_chord",
]
